export const BARANGAYS = [
    'Bagacay',
    'Bajumpandan',
    'Balugo',
    'Banilad',
    'Bantayan',
    'Batinguel',
    'Buñao',
    'Cadawinonan',
    'Calindagan',
    'Camanjac',
    'Candau-ay',
    'Cantil-e',
    'Daro',
    'Junob',
    'Looc',
    'Mangnao-Canal',
    'Motong',
    'Piapi',
    'Poblacion 1 (Tinago)',
    'Poblacion 2 (Upper Luke Wright)',
    'Poblacion 3 (Colon Ext.)',
    'Poblacion 4 (Rizal Boulevard)',
    'Poblacion 5 (Silliman Area)',
    'Poblacion 6 (Cambagroy)',
    'Poblacion 7 (Mangga)',
    'Poblacion 8 (Cervantes Street)',
    'Pulantubig',
    'Tabuc-tubig',
    'Taclobo',
    'Talay'
];
